name: ossproj_comfyride
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_staggered_grid_view: ^0.7.0
  firebase_core: ^2.28.0
  firebase_database: ^10.0.15
  cloud_firestore: ^4.16.0
  http: ^1.2.1
  image_network: ^2.5.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
  - assets/123.jpg